//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StomerijBasiliek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klant()
        {
            this.Werkorder = new HashSet<Werkorder>();
        }
    
        public System.Guid Id { get; set; }
        public int KlantNummer { get; set; }
        public string Voornaam { get; set; }
        public string Voorvoegsel { get; set; }
        public string Achternaam { get; set; }
        public string Straat { get; set; }
        public string Huisnr { get; set; }
        public string PostCode { get; set; }
        public string Plaats { get; set; }
        public string Telefoonvast { get; set; }
        public string TelefoonMobiel { get; set; }
        public string Email { get; set; }
        public int Voorkeur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Werkorder> Werkorder { get; set; }
    }
}
